name: mci-prog-code
title: null

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: false
  input: GFM
  syntax_highlighter_opts:
    block:
      line_numbers: true

